export const STUDENT_ATTENDANCE_REQUEST = 'STUDENT_ATTENDANCE_REQUEST'
export const STUDENT_ATTENDANCE_SUCCESS = 'STUDENT_ATTENDANCE_SUCCESS'
export const STUDENT_ATTENDANCE_FAIL = 'STUDENT_ATTENDANCE_FAIL'