export const ISSUE_BOOK_REQUEST = 'ISSUE_BOOK_REQUEST'
export const ISSUE_BOOK_SUCCESS = 'ISSUE_BOOK_SUCCESS'
export const ISSUE_BOOK_FAIL = 'ISSUE_BOOK_FAIL'
export const ISSUE_BOOK_RESET = 'ISSUE_BOOK_RESET'
