export const UPLOAD_ASSIGNEMNT_REQUEST = 'UPLOAD_ASSIGNEMNT_REQUEST'
export const UPLOAD_ASSIGNEMNT_SUCCESS = 'UPLOAD_ASSIGNEMNT_SUCCESS'
export const UPLOAD_ASSIGNEMNT_FAIL = 'UPLOAD_ASSIGNEMNT_FAIL'
export const UPLOAD_ASSIGNEMNT_RESET = 'UPLOAD_ASSIGNEMNT_RESET'