export const UPLOAD_ASSIGNEMNT_REQUEST = 'UPLOAD_ASSIGNEMNT_REQUEST'
export const UPLOAD_ASSIGNEMNT_SUCCESS = 'UPLOAD_ASSIGNEMNT_SUCCESS'
export const UPLOAD_ASSIGNEMNT_FAIL = 'UPLOAD_ASSIGNEMNT_FAIL'
export const UPLOAD_ASSIGNEMNT_RESET = 'UPLOAD_ASSIGNEMNT_RESET'

export const QUIZ_QUESTION_REQUEST = 'QUIZ_QUESTION_REQUEST'
export const QUIZ_QUESTION_SUCCESS = 'QUIZ_QUESTION_SUCCESS'
export const QUIZ_QUESTION_FAIL = 'QUIZ_QUESTION_FAIL'
export const QUIZ_QUESTION_RESET = 'QUIZ_QUESTION_RESET'