export const TEACHER_ASSIGNMENT_DETAILS_REQUEST = 'TEACHER_ASSIGNMENT_DETAILS_REQUEST'
export const TEACHER_ASSIGNMENT_DETAILS_SUCCESS = 'TEACHER_ASSIGNMENT_DETAILS_SUCCESS'
export const TEACHER_ASSIGNMENT_DETAILS_FAIL = 'TEACHER_ASSIGNMENT_DETAILS_FAIL'

export const CREATE_ASSIGNMENT_REQUEST = 'CREATE_ASSIGNMENT_REQUEST'
export const CREATE_ASSIGNMENT_SUCCESS = 'CREATE_ASSIGNMENT_SUCCESS'
export const CREATE_ASSIGNMENT_FAIL = 'CREATE_ASSIGNMENT_FAIL'
